# Default values for zwavejs2mqtt.
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/charts/tree/master/charts/common

image:
  repository: zwavejs/zwavejs2mqtt
  pullPolicy: IfNotPresent
  tag: 4.5.2

strategy:
  type: Recreate

# 5=tty 20=dialout 24=cdrom
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
  supplementalGroups: [5, 20, 24]

# # See more environment variables in the zwavejs2mqtt documentation
# https://zwave-js.github.io/zwavejs2mqtt/#/guide/env-vars
env: {}
  # OZW_NETWORK_KEY:

probes:
  liveness:
    enabled: true
    # custom: true
    # spec:
    #   failureThreshold: 5
    #   httpGet:
    #     path: /health
    #     port: http
    #     httpHeaders:
    #       - name: Accept
    #         value: text/plain
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    #   timeoutSeconds: 10
  readiness:
    enabled: true
    # custom: true
    # spec:
    #   failureThreshold: 5
    #   httpGet:
    #     path: /health
    #     port: http
    #     httpHeaders:
    #       - name: Accept
    #         value: text/plain
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    #   timeoutSeconds: 10
  startup:
    enabled: false
    # custom: true
    # spec:
    #   failureThreshold: 5
    #   httpGet:
    #     path: /health
    #     port: http
    #     httpHeaders:
    #       - name: Accept
    #         value: text/plain
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    #   timeoutSeconds: 10

service:
  main:
    ports:
      main:
        port: 8091
  ws:
    enabled: true
    type: ClusterIP
    ports:
      ws:
        enabled: true
        port: 3000
        protocol: TCP

# Privileged may be required if USB controller is accessed directly through the host machine
# securityContext:
#   privileged: true

persistence:
  config:
    enabled: true
    mountPath: "/config"
    emptyDir:
      enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""

# Path to your zwave device in the container
additionalVolumeMounts: []
#  - name: usb
#    mountPath: /dev/serial/by-id/usb-0658_0200-if00

# Path to your zwave device on the host
additionalVolumes: []
#  - name: usb
#    hostPath:
#      path: /dev/serial/by-id/usb-0658_0200-if00

# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: app
#           operator: In
#           values:
#           - zwave-controller
