# Default values for rollease2mqtt.
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/charts/tree/master/charts/common

image:
  repository: quentinsf/image-amd64-rollease2mqtt
  pullPolicy: IfNotPresent
  tag: latest

strategy:
  type: Recreate

# 5=tty 20=dialout 24=cdrom
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
  supplementalGroups: [5, 20, 24]

env: {}
  # OZW_NETWORK_KEY:
  # device: /dev/ttyACM0

probes:
  liveness:
    enabled: true
    # custom: true
    # spec:
    #   failureThreshold: 5
    #   httpGet:
    #     path: /health
    #     port: http
    #     httpHeaders:
    #       - name: Accept
    #         value: text/plain
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    #   timeoutSeconds: 10
  readiness:
    enabled: true
    # custom: true
    # spec:
    #   failureThreshold: 5
    #   httpGet:
    #     path: /health
    #     port: http
    #     httpHeaders:
    #       - name: Accept
    #         value: text/plain
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    #   timeoutSeconds: 10
  startup:
    enabled: false
    # custom: true
    # spec:
    #   failureThreshold: 5
    #   httpGet:
    #     path: /health
    #     port: http
    #     httpHeaders:
    #       - name: Accept
    #         value: text/plain
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    #   timeoutSeconds: 10

#service:
#  main:
#    ports:
#      main:
#        port: 8091
#  ws:
#    enabled: true
#    type: ClusterIP
#    ports:
#      ws:
#        enabled: true
#        port: 3000
#        protocol: TCP

# Privileged may be required if USB controller is accessed directly through the host machine
# securityContext:
#   privileged: true

persistence:
  config:
    enabled: true
    mountPath: "/data"
    type: emptyDir


# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: app
#           operator: In
#           values:
#           - zwave-controller
